### ISSUE TITLE
Error:Could not get unknown property 'transformNative_libsWithSyncJniLibsForRelease' for projectof type org.gradle.api.Project.

### ISSUE THREAD

**Issue by dijiubuzhan** [Vigi0303/fat-aar-plugin#9]
how to slove it

**Comment by vigidroid** [comment]
Provide your configuration.
1. gradle wrapper version
2. android gradle plugin version

**Comment by dijiubuzhan** [comment]
Thank you for attention.the problem have been sloved when plugin version is changed to 2,2,3.
Does it support  embedded aar like this:  embedded(name: 'myaar123', ext: 'aar'),when i set defaultPublishConfig 'release' error occur that can not find signal in R.java

**Comment by dijiubuzhan** [comment]
when i remove the belows sentences,the  R.java error sloved.hope it function well.
// Generate R.java files
        /*compileReleaseJavaWithJavac.dependsOn generateRJava
        generateRJava.dependsOn processReleaseResources*/

**Comment by oscarcpozas** [comment]
Hey @Vigi0303 can you update the plugin to support gradle android plugin 2.3.0 or later?

**Comment by vigidroid** [comment]
@oscarcpozas I'm afraid not. To maintain such code is so terrible since the unfriendly and unstable api of the android gradle plugin. I had to take much time on this before. And I felt more distressed just when 2.3.0 came out. 
Maybe I will proceed someday when I have enough will. Or you commit an idea even a pull request to push it. :smile:
